baseURL = "http://localhost:1313/"
title = "વચનામૃત"  # Default title (Gujarati)
theme = "hugo-book"
defaultContentLanguage = "gu"

[params]
  BookSection = "docs"
  BookSearch = true
  BookTheme = "light"

[languages]
  [languages.gu]
    languageName = "ગુજરાતી"
    weight = 1
    title = "વચનામૃત"
    [languages.gu.params]
      BookRepo = "https://github.com/uddhavgyan/original-vachanamrut"
      BookSearchPlaceholder = "શોધો..."

  [languages.hi]
    languageName = "हिंदी"
    weight = 2
    title = "वचनामृत"
    [languages.hi.params]
      BookSearchPlaceholder = "खोजें..."

  [languages.en]
    languageName = "English"
    weight = 3
    title = "Vachanamrut"
    [languages.en.params]
      BookSearchPlaceholder = "Search..."