baseURL = "http://localhost:1313/"
title = "Vachanamrut"
theme = "hugo-book"

defaultContentLanguage = "gu"

[params]
  # BookSection = "docs"      # Use content/docs for sidebar menu
  BookTheme = "light"       # Light mode (clean white background)
  BookSearch = true         # Enable search bar
  BookPortableLinks = true  # Offline caching (optional)

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


   